### ISSUE TITLE
Data Collection System

### ISSUE THREAD

**Issue by ShuangMa156** [jackzou233/EventHDR#3]
Dear Zou, how can the fields of view of three cameras be strictly aligned for spatial accuracy?
![成像系统](https://github.com/user-attachments/assets/29a9515e-0ea0-4bfb-803d-6924c12a76c5)

**Comment by yunhao-zou** [comment]
Hi, all the three cameras share the same optical path, and we also postprocess for spatial alignment. You can also refer to our tutorial for more information: https://www.youtube.com/watch?v=nHax5w10zXc

**Comment by ShuangMa156** [comment]
Thank you for your sharing information!
